@ECHO OFF
h2oforth.exe %1 %2 %3 %4 %5 %6 %7 %8 %9
IF %ERRORLEVEL% EQU 0 ECHO OK
IF %ERRORLEVEL% EQU 1 ECHO HELP
IF %ERRORLEVEL% EQU 2 ECHO UNKNOWN_PARAMETER
IF %ERRORLEVEL% EQU 3 ECHO CODE_NOTFOUND
IF %ERRORLEVEL% EQU 4 ECHO BLOCKS_NOTFOUND
IF %ERRORLEVEL% EQU 5 ECHO FILE_NOTFOUND
